version: '3'
services:

# wordpress container
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_HOST=db
    networks: 
      - if_wordpress


# mysql container
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
    networks: 
      - if_wordpress


# nginx-container
  loadbalancer-nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - wordpress
    networks: 
      - if_wordpress


networks:
  if_wordpress: